version: '3.8'
services:
  postgres:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: citual_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: peoplesoft
    ports:
      - "5435:5432"
    volumes:
      - db_data:/var/lib/postgresql/data


volumes:
  db_data:
