// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	AssignRoleToUser(ctx context.Context, arg AssignRoleToUserParams) error
	CreateClient(ctx context.Context, arg CreateClientParams) (FositeClients, error)
	CreateRole(ctx context.Context, arg CreateRoleParams) (Roles, error)
	CreateSession(ctx context.Context, arg CreateSessionParams) error
	CreateTenant(ctx context.Context, arg CreateTenantParams) (Tenants, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (Users, error)
	CreateUserSession(ctx context.Context, arg CreateUserSessionParams) (UserSessions, error)
	DeleteClient(ctx context.Context, id string) error
	DeleteRole(ctx context.Context, arg DeleteRoleParams) error
	DeleteSessionByType(ctx context.Context, arg DeleteSessionByTypeParams) (int64, error)
	DeleteUser(ctx context.Context, arg DeleteUserParams) error
	DeleteUserSession(ctx context.Context, token string) error
	DeleteUserSessionsByUserID(ctx context.Context, userID uuid.UUID) error
	GetActiveClient(ctx context.Context, id string) (FositeClients, error)
	GetClient(ctx context.Context, id string) (FositeClients, error)
	GetRole(ctx context.Context, arg GetRoleParams) (Roles, error)
	GetRoleByCode(ctx context.Context, arg GetRoleByCodeParams) (Roles, error)
	GetSession(ctx context.Context, arg GetSessionParams) (FositeSessions, error)
	GetTenant(ctx context.Context, id uuid.UUID) (Tenants, error)
	GetUser(ctx context.Context, arg GetUserParams) (Users, error)
	GetUserByEmail(ctx context.Context, email string) (Users, error)
	GetUserSessionByToken(ctx context.Context, token string) (GetUserSessionByTokenRow, error)
	ListClients(ctx context.Context, tenantID uuid.UUID) ([]FositeClients, error)
	ListPublicClients(ctx context.Context) ([]FositeClients, error)
	ListRoles(ctx context.Context, tenantID uuid.UUID) ([]Roles, error)
	ListTenants(ctx context.Context) ([]Tenants, error)
	ListUserRoles(ctx context.Context, userID uuid.UUID) ([]Roles, error)
	ListUsers(ctx context.Context, tenantID uuid.UUID) ([]Users, error)
	RemoveRoleFromUser(ctx context.Context, arg RemoveRoleFromUserParams) error
	RevokeSessionByRequestId(ctx context.Context, requestID string) error
	RevokeSessionByRequestIdAndType(ctx context.Context, arg RevokeSessionByRequestIdAndTypeParams) error
	ToggleClientStatus(ctx context.Context, arg ToggleClientStatusParams) error
	UpdateClientConfig(ctx context.Context, arg UpdateClientConfigParams) error
	UpdateClientSecret(ctx context.Context, arg UpdateClientSecretParams) error
	UpdateTenant(ctx context.Context, arg UpdateTenantParams) error
	UpdateUser(ctx context.Context, arg UpdateUserParams) error
}

var _ Querier = (*Queries)(nil)
