// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (
    id,
    tenant_id,
    first_name,
    last_name,
    email,
    mobile,
    password_hash,
    is_super_admin,
    is_active
) VALUES (
             $1, $2, $3, $4, $5, $6, $7, $8, $9
         )
RETURNING id, tenant_id, first_name, last_name, email, mobile, password_hash, is_super_admin, authz_version, is_active, email_verified_at, mobile_verified_at, created_at, updated_at
`

type CreateUserParams struct {
	ID           uuid.UUID `json:"id"`
	TenantID     uuid.UUID `json:"tenant_id"`
	FirstName    string    `json:"first_name"`
	LastName     string    `json:"last_name"`
	Email        string    `json:"email"`
	Mobile       *string   `json:"mobile"`
	PasswordHash string    `json:"password_hash"`
	IsSuperAdmin bool      `json:"is_super_admin"`
	IsActive     bool      `json:"is_active"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (Users, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.ID,
		arg.TenantID,
		arg.FirstName,
		arg.LastName,
		arg.Email,
		arg.Mobile,
		arg.PasswordHash,
		arg.IsSuperAdmin,
		arg.IsActive,
	)
	var i Users
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.FirstName,
		&i.LastName,
		&i.Email,
		&i.Mobile,
		&i.PasswordHash,
		&i.IsSuperAdmin,
		&i.AuthzVersion,
		&i.IsActive,
		&i.EmailVerifiedAt,
		&i.MobileVerifiedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM users
WHERE id = $1 AND tenant_id = $2
`

type DeleteUserParams struct {
	ID       uuid.UUID `json:"id"`
	TenantID uuid.UUID `json:"tenant_id"`
}

func (q *Queries) DeleteUser(ctx context.Context, arg DeleteUserParams) error {
	_, err := q.db.Exec(ctx, deleteUser, arg.ID, arg.TenantID)
	return err
}

const getUser = `-- name: GetUser :one
SELECT id, tenant_id, first_name, last_name, email, mobile, password_hash, is_super_admin, authz_version, is_active, email_verified_at, mobile_verified_at, created_at, updated_at FROM users
WHERE id = $1 AND tenant_id = $2
`

type GetUserParams struct {
	ID       uuid.UUID `json:"id"`
	TenantID uuid.UUID `json:"tenant_id"`
}

func (q *Queries) GetUser(ctx context.Context, arg GetUserParams) (Users, error) {
	row := q.db.QueryRow(ctx, getUser, arg.ID, arg.TenantID)
	var i Users
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.FirstName,
		&i.LastName,
		&i.Email,
		&i.Mobile,
		&i.PasswordHash,
		&i.IsSuperAdmin,
		&i.AuthzVersion,
		&i.IsActive,
		&i.EmailVerifiedAt,
		&i.MobileVerifiedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, tenant_id, first_name, last_name, email, mobile, password_hash, is_super_admin, authz_version, is_active, email_verified_at, mobile_verified_at, created_at, updated_at FROM users
WHERE email = $1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (Users, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i Users
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.FirstName,
		&i.LastName,
		&i.Email,
		&i.Mobile,
		&i.PasswordHash,
		&i.IsSuperAdmin,
		&i.AuthzVersion,
		&i.IsActive,
		&i.EmailVerifiedAt,
		&i.MobileVerifiedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listUsers = `-- name: ListUsers :many
SELECT id, tenant_id, first_name, last_name, email, mobile, password_hash, is_super_admin, authz_version, is_active, email_verified_at, mobile_verified_at, created_at, updated_at FROM users
WHERE tenant_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListUsers(ctx context.Context, tenantID uuid.UUID) ([]Users, error) {
	rows, err := q.db.Query(ctx, listUsers, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Users{}
	for rows.Next() {
		var i Users
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.FirstName,
			&i.LastName,
			&i.Email,
			&i.Mobile,
			&i.PasswordHash,
			&i.IsSuperAdmin,
			&i.AuthzVersion,
			&i.IsActive,
			&i.EmailVerifiedAt,
			&i.MobileVerifiedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateUser = `-- name: UpdateUser :exec
UPDATE users
SET
    first_name = $2,
    last_name = $3,
    mobile = $4,
    updated_at = NOW()
WHERE id = $1 AND tenant_id = $5
`

type UpdateUserParams struct {
	ID        uuid.UUID `json:"id"`
	FirstName string    `json:"first_name"`
	LastName  string    `json:"last_name"`
	Mobile    *string   `json:"mobile"`
	TenantID  uuid.UUID `json:"tenant_id"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) error {
	_, err := q.db.Exec(ctx, updateUser,
		arg.ID,
		arg.FirstName,
		arg.LastName,
		arg.Mobile,
		arg.TenantID,
	)
	return err
}
